### ISSUE TITLE
Improve performance for granular change on graph attributes

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/ipycytoscape#105]
This kind of "regression" was introduced on https://github.com/QuantStack/ipycytoscape/pull/104

So what this PR is doing is allowing the user to create granular changes to the graph to the level of each node and each edge, the problem is that to be able to show this result on the frontend the graph must be renderized every time a new change is made.
That means that if you change the `style` of 100 nodes, your graph will be renderized 100x, and that's not good. 

This happens because we don't have memory to deal with the nodes and edges, currently every time something is changed we're just calling `value_changed` and then rerendering everything from scratch.

So, a possible improvement idea here would be having some kind of memory to store the nodes and edges that should be updated and only when this interaction is over we rerender everything.

Not sure what's the best way to do this and when we should rerender everything exactly. Mainly writing this so we don't forget about this performance issue that might be incapacitating for people with really big amounts of data.

**Comment by christiandreher** [comment]
Why not just set a flag? Do not re-render if it is set, and render once when it is reset? Kinda like a render mutex.

I don't know how to pass the information to the typescript side, but there you could just check for the flag [here](https://github.com/QuantStack/ipycytoscape/pull/104/files#diff-34553059c4dd30c842fd5e8e2e4ff290R239), right?

You'd just have to install a separate event handler for changes on the flag so that you don't miss a render.

This could be combined with the neat `__enter__` and `__exit__` functions, like:

``` python
widget = ipycytoscape.CytoscapeWidget()
# ...
# Do heavy changes on the graph now:
with ipycytoscape.lock_render(widget.graph) as g:
  for edge in g.edges:
    edge.classes += " new-class"
```

It's just an idea though, maybe I'm missing something obvious...

**Comment by ianhi** [comment]
I think having a context manager is really neat idea. @christiandreher  I think you'd need to put a check for a continuous updates flag here: https://github.com/QuantStack/ipycytoscape/blob/4f2c726c69f5a0622d575cca9bd3c35535ed7fa1/src/widget.ts#L371-L375

then you add a Bool attribute to the python object like this `continuous_updates = Bool(True).tag(sync=True)` and access it in typescript (from inside the model) with `this.get('continuous_updates')`. Or to get it from a inside a view `this.model.get('continuous_updates')`

@marimeireles I think I contextmanager may be a generally useful thing but for this problem I'd like to continue to evangelize the ideas in https://github.com/QuantStack/ipycytoscape/issues/96 - moving more information into the model and then having changes affect views only through the cytoscapejs apis. In this case it would be https://js.cytoscape.org/#eles.addClass
