### ISSUE TITLE
"popper" dependency is probably spurious

### ISSUE THREAD

**Issue by telamonian** [QuantStack/ipycytoscape#107]
On npmjs, "popper" is a package with the goal of supporting "Realtime Cross-Browser Automation", and which hasn't been updated in 3 years: https://www.npmjs.com/package/popper. Thus, the

https://github.com/QuantStack/ipycytoscape/blob/4f2c726c69f5a0622d575cca9bd3c35535ed7fa1/package.json#L61

dependency is probably wrong. This line should be removed from `package.json`.

Just to be safe, I did a text search of the `ipycytoscape` project. The only reference to "popper" is here:

https://github.com/QuantStack/ipycytoscape/blob/b662ec1538564676ffc0c2334ff77dd407a7a1a0/src/widget.ts#L24-L32

`popper.js`, on the other hand, is a UI component library, and seems to be what was intended: https://www.npmjs.com/package/popper.js/v/1.14.3. However, `ipycytoscape` only uses popper through the `cytoscape-popper` package, which already includes `popper.js` as a dependency, so there's no need to include `popper.js` as an explicit dependency of this package.

**Comment by telamonian** [comment]
On a practical level, the line

https://github.com/QuantStack/ipycytoscape/blob/4f2c726c69f5a0622d575cca9bd3c35535ed7fa1/package.json#L61

seems to be causing trouble for my automated procurement software. For whatever reason, it can't seem to correctly read the dependencies (for vuln scanning) of this 3+ year old package. If there isn't a good reason to keep it, can you please remove this dep?

**Comment by ianhi** [comment]
@marimeireles I think this makes total sense to remove. Relatedly should `@types/cytoscape` be a devDependency instead of a dependency?

**Comment by telamonian** [comment]
I've opened a PR that removed the "popper" dep over at #108
