### ISSUE TITLE
Fix regressions on examples

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/ipycytoscape#112]
Because we broke backward compatibility some examples stopped working.

- NetworkX example

No real clue on what's wrong after looking at it briefly. I'm under the impression that it broke after merging https://github.com/QuantStack/ipycytoscape/pull/54

- Tip gene example

Apparently the `deepcopy` hack for `set_layout` is no longer working.
That might be because I fixed the synchronization between front and backend? Seems unlikely, but other than that, can't think of anything else that's causing it. I think simply changing the way we deal with this to use the new API should fix it...

**Comment by MridulS** [comment]
@marimeireles https://github.com/QuantStack/ipycytoscape/pull/113 should fix the first issue here.

**Comment by marimeireles** [comment]
RIght, partially fixed by @MridulS.
The tip gene example is still broken. Will update this in a new version now though.

**Comment by ianhi** [comment]
>  That might be because I fixed the synchronization between front and backend? Seems unlikely, but other than that, can't think of anything else that's causing it. I think simply changing the way we deal with this to use the new API should fix it...

There were two issues, both introduced by me. 
1. Loading the widget's layout rather than the cytoscape_layout
2. Using the cytoscapejs api you need to also run the api, not just set it

should be fixed by linked PR

**Comment by marimeireles** [comment]
> Using the cytoscapejs api you need to also run the api, not just set it

Right!
Cool! =)
Thank you so much for the catch @ianhi.

**Comment by marimeireles** [comment]
Fixed.
Thanks people! 🌸
