### ISSUE TITLE
Add python version requirement

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/ipycytoscape#12]
As originally suggested by @marcelotrevisani in https://github.com/conda-forge/staged-recipes/pull/11015

We should have

```
python_requires=">=3.0"
```

in setup.py

**Comment by marimeireles** [comment]
Sorry I missed this in my last update. So I'll change [this](https://github.com/QuantStack/ipycytoscape/blob/master/setup.py#L88-L90) +will add some info for [pypi](https://packaging.python.org/tutorials/packaging-projects/#setup-args) in my next one.
Thanks <3

**Comment by marimeireles** [comment]
This was attend to.
