### ISSUE TITLE
release 1.0.3

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#121]
The currently released version is pretty broken for networkx (no isolated nodes + classes don't work) This was fixed by https://github.com/QuantStack/ipycytoscape/pull/117 but never released.

It would also be good to include https://github.com/QuantStack/ipycytoscape/pull/118 in a release but I think the fixes in #117 are much more critical. For example repos like this one are running into this breakage https://github.com/Abhinay1997/exploring_ipcytoscape/blob/master/ipycytoscape_doesnt_render_isolated_nodes_with_networkx.ipynb

@marimeireles I have no sense of how difficult it is make a release - if its difficult I think it can be automated by github actions that would maybe make things easier?

**Comment by ianhi** [comment]
If you're interested in releasing with via github this jlab-git PR is probably the approach to follow https://github.com/jupyterlab/jupyterlab-git/pull/655

**Comment by marimeireles** [comment]
Hey @ianhi, it's not actually hard, as you can see in my release commit here for instance: https://github.com/QuantStack/ipycytoscape/commit/139fdcdeec03f689bab6f56b7744dd253a65d08d

And yeah, looking at your link I think we could do the same. Even though I have no clue on how to use this github action thing. Like how to trigger and stuff, but might be cool to learn!

We have to install the pertinent dependencies and change to `twine upload dist/ipycytoscape*` in the `publish.yml`, in the `release` file we have to check for the right version places and change it too. 

This github action stuff doesn't change code, though, right?
We'd have to at least do the same things as in my commit and tag it with a version tag so pypi could pick it up as a package.

**Comment by ianhi** [comment]
> might be cool to learn!

For sure it would be! Maybe that should get it's own issue?

@marimeireles do you think we should deal with #118 before a small release so that all of networkx works? Or is #117 reason enough (I'd vote that it is), or that we should wait for other things?

**Comment by marimeireles** [comment]
> For sure it would be! Maybe that should get it's own issue?

Probably!

Will do it now, it's not a lot of work anyways =)

**Comment by marimeireles** [comment]
Ok, the pypi version is out, in a few minutes we should have a conda too! :)
Thanks @ianhi

**Comment by ianhi** [comment]
hooray! thanks

It would be cool to have tests that would prevent errors like the one that broke networkx classes/lonely nodes.
