### ISSUE TITLE
Add screencast to the README

### ISSUE THREAD

**Issue by jtpio** [QuantStack/ipycytoscape#13]
Congrats on the first release!

Since this widget will probably be getting more and more attention, it would be nice to have a screencast in the README to get an idea of what it looks like.

**Comment by marimeireles** [comment]
Hey, thanks :)
Yeah, the rules for a screencast are quite restrict though, right? :p
It has to be made in a jupyter lab and do I have to use specific dimensions?

**Comment by SylvainCorlay** [comment]
Maybe we should start with a screenshot, since it will quickly be outdated - and gifs are large.

**Comment by marimeireles** [comment]
The frontend won't actually change much.

**Comment by SylvainCorlay** [comment]
Although the screenshots may include a notebook cell. Also, outdated gifs stay in the git history.

**Comment by jtpio** [comment]
For now the screencast could be uploaded to GitHub (drag and drop in a comment textbox), and the URL used in the README. To save on the size.

**Comment by SylvainCorlay** [comment]
> For now the screencast could be uploaded to GitHub (drag and drop in a comment textbox), and the URL used in the README. To save on the size.

that's funny.

**Comment by jtpio** [comment]
The trade-off is that they don't render offline of course.

**Comment by marimeireles** [comment]
![cytoscape](https://user-images.githubusercontent.com/17600982/76328068-bbbbcf00-62e2-11ea-93ed-01ba392ac50c.gif)

**Comment by marimeireles** [comment]
Closing the issue because I added everything I could think of it'd be useful at the moment on the readme. 
Thanks @jtpio and @SylvainCorlay 🌸

**Comment by jtpio** [comment]
This looks great, thanks!
