### ISSUE TITLE
update copyright to ipycytoscape contributors

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#132]
Most of the copyright statements currently say Mariana Meireles, although @marimeireles has added my name to a few of them :) 

However at present there are 16 people who have contributed to this repository so I propose to change all the copyright statements to read `ipycytoscape contributors` following https://github.com/jtpio/ipylab/pull/47

**Comment by marimeireles** [comment]
Yeah, that's a great idea :)
Let's do this!
