### ISSUE TITLE
examples of ipycytoscape from Networkx not working

### ISSUE THREAD

**Issue by joseberlines** [QuantStack/ipycytoscape#136]

**Comment by marimeireles** [comment]
Hey @joseberlines is everything okay?
The examples are actually working? Thanks!

**Comment by joseberlines** [comment]
Sorry, I am like a bit of a beginner, I wanted to completly delete the issue but was not able. I am sorry for disturbing. All working now. I realised my ipycytoscape was old version

**Comment by marimeireles** [comment]
It's fine!
No problem at all :)
I was afraid we were lacking behind in our versions because there's been a while since we released one.
Feel free to ask questions!
Cheers.
