### ISSUE TITLE
Contribute your dashboard!

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/ipycytoscape#144]
Hey community!

@ianhi and I will present a talk about ipycytoscape on this year's JupyterCon. Just by interacting with you through github I could see that we have some users with amazing user cases. You use ipycytoscape in ways that I could never imagine myself.

If you can and you're interested in sharing a little bit of your workflow and how do you use ipycytoscape with us, it'd be amazing! Of course we'd give you the proper credit for your work, the point here is to show diverse ways of using ipycytoscape.

Thanks a lot! 🌸

**Comment by marimeireles** [comment]
(ping @stefco I remember being amazed by how different ipycytoscape used in your screencasts)

**Comment by stefco** [comment]
@marimeireles I'd love to share! I can take some video of the pipeline/full interface in use, show some data products, summarize the use case, write a bit about the wonderful experience I had contributing to ipycytoscape--whatever you like. What's the format/what kind of contribution would you like.

I'm developing some image compression/analysis tech that I'd like to spin off into a startup (or at least a job) after i graduate ("soon"), so getting some exposure would be great as well.

**Comment by marimeireles** [comment]
Hey @stefco! That's awesome! Thank you so much!
So, I think for the talk format it'd be interesting to have either screencasts or screenshots of your dashboard and a summary of the user case. I'm also interested in learning why did you choose ipycytoscape specifically and yeah, anything else you wanna add would be a cool bonus! :) I'm always interested in learning more about the community.

> I'm developing some image compression/analysis tech that I'd like to spin off into a startup (or at least a job) after i graduate ("soon"), so getting some exposure would be great as well.

And that's your user case for ipycytoscape? If it is I'd be happy to cite it :)
If you want to move this conversation to a private chat: https://gitter.im/marimeireles

**Comment by stefco** [comment]
@marimeireles It's not my cyto use case, just what i'm currently working on. If you're introducing people, I would mention that as my current project. 

My actual cyto use case, which is what i would present on, is a control panel for my [low latency multi-messenger astrophysics analysis pipeline](https://multimessenger.science), showing a full file dag with pipeline steps as nodes and dependencies as edges. I used color-coding to indicate pipeline state and allowed users to select and examine individual steps, which is what i would present on. I'll also describe how great and easy it was contributing to ipycytoscape.

How long should i aim for? Is 2 minutes good? More, less?

What's the time frame for getting you a screencast? It would be easiest for me to do this over the weekend. 

Thanks!

**Comment by marimeireles** [comment]
> My actual cyto use case, which is what i would present on, is a control panel for my low latency multi-messenger astrophysics analysis pipeline, showing a full file dag with pipeline steps as nodes and dependencies as edges. I used color-coding to indicate pipeline state and allowed users to select and examine individual steps, which is what i would present on. I'll also describe how great and easy it was contributing to ipycytoscape.

That's amazing!!!
@ianhi do you have an input here? Any idea for this kind of contribution?
I think we could show something shorter in the presentation (2mins seems like a good time window, what do you think?) and then we can leave a link in the slides where people can find more information about the projects.

And then @stefco you're free to add info about your startup project there.
If it's anyhow related to ipycytoscape I'd be happy to talk about it on the talk, but if it's not, I don't think it makes much sense including it, unfortunately.

**Comment by marimeireles** [comment]
Also, maybe @MridulS is also using ipycytoscape to do cool graph things?

**Comment by MridulS** [comment]
not really 😅

I'm just playing around with ipycytoscape right now :)

**Comment by marimeireles** [comment]
Still appreciated! :p

**Comment by stefco** [comment]
@marimeireles cool, I'll work on something over the weekend and send early next week! Yeah, I would put info about current/future work somewhere and link to it. It's orthogonal to the presentation.

Do you want *just* a screencast or should i make a summary slide as well? I think having both is nicest but it's up to you what fits in best. Happy to send a slide in powerpoint/pages/sheets (whichever is easiest) for you to stick in the presentation.

**Comment by marimeireles** [comment]
Hey @stefco I'd be happy to get some summary from you of course! :)
Thank you very much. Once the slides are done I'll send you a copy for you to approve (before the talk).

**Comment by marimeireles** [comment]
Hey @stefco any progress on this?
We have until the end of this week to put everything together. Anything you contribute would be super cool. If the screencast is too much, your user cases with a few screenshots would be fine too.
But no stress if you can't make it either!
Thanks for all :)

**Comment by sven5s** [comment]
Can be closed?

**Comment by marimeireles** [comment]
Yeah, I think so, even though, if anyone is seeing this. We're always interested in your dashboard!
I'm pretty sure it'll help everyone using it :)
