### ISSUE TITLE
Minor documentation issues

### ISSUE THREAD

**Issue by bitbucketboss** [QuantStack/ipycytoscape#178]
https://ipycytoscape.readthedocs.io/en/latest/installing.html#jupyterlab
Revision fb8d47f1

"... conda by doing" appears to be missing text.

"... install the JupyterLab widget manager:" appears to be missing text.

PS: This is an amazing package !

**Comment by marimeireles** [comment]
True! And the sentence immediately below it too.
Please feel free to contribute it if you know how to complete the missing parts :)
Otherwise, I'll add to my backlog. 
Thanks for the kind words and for opening an issue =)

**Comment by ianhi** [comment]
Good catch @bitbucketboss  (also sweet username)
Looking at this I noticed a few other things that need to be corrected:

1. Probably also good to include installing `nodejs` in the conda/mamba commands. 
2. The install instructions in the readme incorrectly point users to `labextension install jupyter-cytoscape`
