### ISSUE TITLE
adding a new node to a graph.

### ISSUE THREAD

**Issue by joseberlines** [QuantStack/ipycytoscape#185]
just published a question in StackOverflow with the following content:

Assuming I have a graph like:

```
railnet= '''{
    "nodes": [
        {"data": { "id": 1,"name":"BER" }},
        {"data": { "id": 2,"name": "MUN"}},
        {"data": { "id": 3,"name": "FRA"}}
        ],
    "edges": [
        {"data": { "id": "BER - MUN", "source": "BER", "target": "MUN" }},
        {"data": { "id": "MUN - FRA", "source": "MUN", "target": "FRA" }},
        {"data": { "id": "FRA - BER", "source": "FRA", "target": "BER" }}
    ]
  }'''
railnetJSON = json.loads(railnet)
ipycytoscape_obj3 = ipycytoscape.CytoscapeWidget()
ipycytoscape_obj3.graph.add_graph_from_json(railnetJSON, directed=False) # I am telling I dont want directions
ipycytoscape_obj3
```
later on I want to add a node to the graph.

the following does not work:

```
new_node_string = '''{"data": { "id": "4", "name":"DOR"}}'''
new_node_json = json.loads(new_node)
print(new_node_json['data']) # the dictionary HAS a key "data"
```
but when doing:

`ipycytoscape_obj.graph.add_node(new_node_json)`
the error is:

`AttributeError: 'dict' object has no attribute 'data'`

Some idea what I am doing wrong? Don't I need the node to be of the type as JSON?

NOTE: So far I don't want to resort to Networkx

https://stackoverflow.com/questions/64953583/adding-a-node-to-an-ipycytoscape-widget

**Comment by MridulS** [comment]
It needs to be `node` object not a JSON one.

``` python

new_node = ipycytoscape.Node()
new_node.data['id'] = 4
new_node.data['name'] = 'DOR'

ipycytoscape_obj3.graph.add_node(new_node)
```

**Comment by MridulS** [comment]
Also the initial JSON should be
```
railnet= '''{
    "nodes": [
        {"data": { "id": "BER"}},
        {"data": { "id": "MUN"}},
        {"data": { "id": "FRA"}}
        ],
    "edges": [
        {"data": { "id": "BER - MUN", "source": "BER", "target": "MUN" }},
        {"data": { "id": "MUN - FRA", "source": "MUN", "target": "FRA" }},
        {"data": { "id": "FRA - BER", "source": "FRA", "target": "BER" }}
    ]
  }'''
```
or
```
railnet= '''{
    "nodes": [
        {"data": { "id": 1,"name":"BER" }},
        {"data": { "id": 2,"name": "MUN"}},
        {"data": { "id": 3,"name": "FRA"}}
        ],
    "edges": [
        {"data": { "id": "BER - MUN", "source": 1, "target": 2 }},
        {"data": { "id": "MUN - FRA", "source": 2, "target": 3 }},
        {"data": { "id": "FRA - BER", "source": 3, "target": 1 }}
    ]
  }'''
```
The edges are created between two `id` of nodes, not the name.

**Comment by sven5s** [comment]
I wrote myself to small helper function to create nodes and edges from dicts:
```
import ipycytoscape

def _set_attributes(instance, data):
    cyto_attrs = ['group', 'removed', 'selected', 'selectable',
                    'locked', 'grabbed', 'grabbable', 'classes', 'position', 'data']
    for k, v in data.items():
        if k in cyto_attrs:
            setattr(instance, k, v)
        else:
            instance.data[k] = v

def add_node(graph, node_dict):
    node = ipycytoscape.Node()
    _set_attributes(node, node_dict)
    graph.add_node(node)

def add_edge(graph, edge_dict, **kwargs):
    edge = ipycytoscape.Edge()
    _set_attributes(edge, edge_dict)
    graph.add_edge(edge, **kwargs)
```
_set_attributes is used from the original source code:
https://github.com/QuantStack/ipycytoscape/blob/26fed38ae6aa5c3bad375cab3ddcf937d84de72b/ipycytoscape/cytoscape.py#L220

It can be used like this:
```
add_edge(cytoscapeobj.graph, {'data': { 'source': 'a', 'target': 'c' }}, directed=True)
add_node(cytoscapeobj.graph, { 'data': { 'id': 'aa', 'name': 'Test', 'list': [1, 2, 3, 4]} })
```

**Comment by joseberlines** [comment]
So this is already WITHIN ipycytoscape I understand.
This might probably override my pull request for adding classes @marimeireles @ianhi .

My funct does the following.  add_class(node, classes)

**Comment by sven5s** [comment]
No, your function has a different purpose. But from an OOP perspective add_class should be a method of Node and Edge.

**Comment by marimeireles** [comment]
Hey peeps, sorry for not being around much, I'm working in another project that's sucking my mind entirely.
Thank you very much for the replies :))

@joseberlines will have a look at your PR right now, sorry for the delay. Does Sven5s's and Mridul's comments answer your question and we can close this one?
