### ISSUE TITLE
Question: Adding attributes to node via JSON data. TypeError: 'Node' object does not support item assignment

### ISSUE THREAD

**Issue by joseberlines** [QuantStack/ipycytoscape#192]
I am trying to assign to a node attributes looping through the key values of a JSON data.
but I get the following error:

```
 new_node = ipycytoscape.Node()
   
...
...
        # rest of the elements
        for key,value in json_row.items():
            new_node[key] = value.  # this is line 52

```

```
---> 52             new_node[key] = value
     53 
     54         ipycytoscape_obj.graph.add_node(new_node)

TypeError: 'Node' object does not support item assignment
```

If I have data in JSON how can I assign this data to the node (to add later on to the ipycytoscape object)

Note: I am working on the pandas data frame implementation as I mentioned in: 
https://github.com/QuantStack/ipycytoscape/issues/128#issuecomment-734487703
and originally in:
https://github.com/QuantStack/ipycytoscape/issues/149#issue-688554574

**Comment by marimeireles** [comment]
Hum... I think for this kind of user case you'd have to create a custom node @joseberlines.
I think @MridulS wrote an example of this at some point? You were doing something really similar to this right? @ianhi may know what I'm talking about.

**Comment by ianhi** [comment]
@joseberlines are you trying to assign attributes that should be synced to the frontend or just generic attributes of the object? for the former everything that the frontend can handle is already present on the object. For the latter you can do something like `set_attr(new_node, key, value)`
