### ISSUE TITLE
add_node vs. add_nodes and add_edge vs. add_edges

### ISSUE THREAD

**Issue by sven5s** [QuantStack/ipycytoscape#195]
Mainly in add_edge and add_edges a lot of code is duplicated. I think both should be combined in one function. The same should be done for add_node and add_nodes.
My idea would be to use extend for both cases because it's not [much slower](https://stackoverflow.com/a/28119966) than append. We could keep both function but let the single function call the one for multiple instances, e.g.
https://github.com/QuantStack/ipycytoscape/blob/26fed38ae6aa5c3bad375cab3ddcf937d84de72b/ipycytoscape/cytoscape.py#L307
```
def add_edge(self, edge, *args, **kwargs):
    self.add_egdes([edge], *args, **kwargs)
```
and
https://github.com/QuantStack/ipycytoscape/blob/26fed38ae6aa5c3bad375cab3ddcf937d84de72b/ipycytoscape/cytoscape.py#L243
```
def add_node(self, node, *args, **kwargs):
    self.add_nodes([node], *args, **kwargs)
```
We wouldn't lose much performace but reduce the code.

Maybe we could combine both function but I can't get a good name that's not misleading.
What's your opinion?

**Comment by ianhi** [comment]
> Maybe we could combine both function but I can't get a good name that's not misleading.

I'm running into the same struggles with naming - so it's probably best to keep two separate functions. 


Overall I agree that we should probably not be duplicating code like this. Though @MridulS wrote most of this code, do you have an opinion?

> We could keep both function but let the single function call the one for multiple instances, e.g.

I like this approach. Anyone is welcome to open a PR implementing this :)

**Comment by MridulS** [comment]
> Overall I agree that we should probably not be duplicating code like this. Though @MridulS wrote most of this code, do you have an opinion?

I like this one and this also fixes the performance issues with communication with the front end.
```
def add_node(self, node, *args, **kwargs):
    self.add_nodes([node], *args, **kwargs)
```

**Comment by sven5s** [comment]
I write the PR at the moment but find a strange behavior, maybe it is desired.
In https://github.com/QuantStack/ipycytoscape/blob/0f16ef70ec8443d2fd182018b074d467cbe7894f/ipycytoscape/cytoscape.py#L307 exists the following block
```
        if directed and "directed" not in edge.classes:
            edge.classes += " directed "
        if multiple_edges and "multiple_edges" not in edge.classes:
            edge.classes += " multiple_edges "
```
But in https://github.com/QuantStack/ipycytoscape/blob/0f16ef70ec8443d2fd182018b074d467cbe7894f/ipycytoscape/cytoscape.py#L362 is no such code.

This means if I add a single edge the class is set but if I want to add multiple edges I had to set the classes attribute previously in the instance.
If I add the above block to add_edges all test are passed, but maybe I miss something

**Comment by sven5s** [comment]
Well, if I add the block
```
        if directed and "directed" not in edge.classes:
            edge.classes += " directed "
        if multiple_edges and "multiple_edges" not in edge.classes:
            edge.classes += " multiple_edges "
```
to add_edges, the input edges is changed. This is not so nice. Maybe we should copy the edge instance, or is the connection intended?

**Comment by ianhi** [comment]
> This means if I add a single edge the class is set but if I want to add multiple edges I had to set the classes attribute previously in the instance.
If I add the above block to add_edges all test are passed, but maybe I miss something

I don't think you've missed something, instead I think you've found a bug! Your proposed cleanup sounds like it will fix this bug so I'm all for it.


> to add_edges, the input edges is changed. This is not so nice. Maybe we should copy the edge instance, or is the connection intended?

I think it needs to be this way, otherwise if you create a `Node` object give it to the graph and then make further changes to it they won't be reflected in the displayed graph. So something like:
```python
my_node = ipycytoscape.Node(....)
G.graph.add_node(my_node)
my_node.grabbable = False
```
wouldn't make sense if we are making a copy.


That said, it is super not nice of us to be change attributes given that this is not mentioned at all in the function docstring. Ideally fixes for this will also include more extensive docstrings explaining to the user what is happening.
