### ISSUE TITLE
Change ipycytoscape CI provider

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/ipycytoscape#196]
Travis is now paid. We have a few options:

* migrate to another server, azure?
* ipycytoscape is and will always be open source so we qualify for asking Travis free credits
* any other idea?

**Comment by MridulS** [comment]
Pretty much all the projects I know moved to GitHub Actions. Anything stopping ipycytoscape  from moving to it?

**Comment by marimeireles** [comment]
No! Had forgot about that one. Thanks @MridulS :)
I have no idea what might be the best option as I only used travis.

**Comment by ianhi** [comment]
+1 to github actions. Very easy to use on github. 

As ever ipycanvas is a good place to look for how to do this. See https://github.com/martinRenou/ipycanvas/blob/master/.github/workflows/main.yml

It's also nice to use a pip cache like I do here:
https://github.com/ianhi/mpl-interactions/blob/5cb80ff27ec31d6501d9e1088fc592dbc62bc6c8/.github/workflows/test.yml#L30-L42

**Comment by ianhi** [comment]
Also, @marimeireles what do you think of automated releases via github actions? You just use the draft release button and then it will generate a wheel and upload to pypi + npm. For example this workflow used on jlab-git https://github.com/jupyterlab/jupyterlab-git/blob/master/.github/workflows/publish.yml
