### ISSUE TITLE
Can ipycytoscape be run in localhost other than jupyter notebook?

### ISSUE THREAD

**Issue by caraevangeline** [QuantStack/ipycytoscape#198]
I want to display the ipycytoscape graph in localhost. 
Any tips or ideas are highly appreciated!
Thanks in advance!

**Comment by marimeireles** [comment]
Hey @caraevangeline I'm not sure about this. I'd say there are ways, like using voila https://github.com/voila-dashboards/voila/
Or maybe depending on your user case even using the cytoscape.js would be an easier approach? If you feel like sharing a bit more about your context maybe I can help more :)
Also https://gitter.im/QuantStack/Lobby people on this chat are more knowledgeable than I in this topic. Feel free to ask your question there too

**Comment by caraevangeline** [comment]
@marimeireles I am trying to visualize a network graph which will have the following features and should be runnable in a server/localhost
1) click and drag nodes
2) Redirect to another page when clicking a node
3) Drill up and down the entire graph
4) Network graph should be able to accumulate different layouts of algorithms
5) hover over the node and display content in tooltip

I initially tried, NetworkX but I don't have the option of click and drag. So I posted the issue in the github forum and I was redirected to use ipycytoscape but again my requirements are not satisfied

PS: I am not a pro in visualization but I am trying the best possible ways to make the network graph look less chaotic and more readable. 
Any suggesstions would really be helpful for me. Thank you!:-)

**Comment by joseberlines** [comment]
@caraevangeline I think you will be able to do all that with ipycytoscape.
What do you actually mean by:
Network graph should be able to accumulate different layouts of algorithms
?
How big is your data? tens? hundreds of nodes?
I am working on a solution where you can input data frames as input to a method that construct the ipycytoscape. Perhaps this might be another use-case. The idea is to manipulate only data frames, and then pass them to a ipycytoscpae graph constructor. 
The graph will have only one layout at a time, but any time you can build it again if data frames data change.

Could that be something that fits your needs?

**Comment by caraevangeline** [comment]
@joseberlines I want to put a drop-down menu mentioning all algorithms (ie. circular, spread, spring, etc) according to user convenience
My data will consist of 1000's of nodes.
Yes, I need one layout at a time. Can ipycytoscape be run in localhost using dash or flask?

**Comment by joseberlines** [comment]
I don't really understand what do you mean by local host.
You can display it with voila, which is I would say the natural way. 
https://github.com/voila-dashboards/voila

I still don't have install in this computer. I will do it straight away and will post snapshots.
As for your drop down menu I guess you are thinking about ipywidgets.

So my approach (pandas) is perfectly applicable to your case. Every time the user choses a layout you re-render your graph.

**Comment by caraevangeline** [comment]
@joseberlines Thank you!
What I mean by localhost is, I want the python program to render the graph in a web page

**Comment by joseberlines** [comment]
> @joseberlines Thank you!
> What I mean by localhost is, I want the python program to render the graph in a web page

Perfect. Then voila is the answer. Follow the instructions in the voila page. if all goes well in a minute you are up and running.
first install voila and then the jupyter lab extension. 
Then you will have a button in your jupyter lab to render any notebook with voila. Just click and go.

**Comment by joseberlines** [comment]
See here in local host with voila:
<img width="995" alt="Screenshot 2020-12-12 at 17 22 14" src="https://user-images.githubusercontent.com/33203439/101989137-af640880-3c9e-11eb-8036-583afeb16264.png">

See on the top localhost

**Comment by caraevangeline** [comment]
@joseberlines Thank you! Can the interactive graph alone be hosted in localhost instead of the entire code?

**Comment by caraevangeline** [comment]
@joseberlines Thanks a lot! 
Just a last question
Can the interactive graph alone be hosted in localhost instead of the entire code?

**Comment by joseberlines** [comment]
I don't think so. 
What voila does is rendering the output of the cells of the notebook.
You can make a notebook that outputs nevertheless ONLY the graph. 
Your cells should not output anything and you should not have any markdown cells in the notebook.
This is actually the way to go.
You do all your calculations and you output only "the widgets" including the dropdown menu and the Graph.

**Comment by caraevangeline** [comment]
@joseberlines Thank you for all your replies!

**Comment by joseberlines** [comment]
look this: https://joseberlines.medium.com/learning-and-visualising-graphs-with-ipycytoscape-1ca150f24933

**Comment by caraevangeline** [comment]
@joseberlines Okay, Thank you. It really helps!

**Comment by joseberlines** [comment]
In the coming days I will publish a second article in the series in medium Exactly with the problem you mentioned.
stay tuned.
now I think you can close.

**Comment by caraevangeline** [comment]
> this is what I meant with voila once installed:
> <img alt="Screenshot 2020-12-12 at 19 56 08" width="929" src="https://user-images.githubusercontent.com/33203439/101992534-599a5b00-3cb4-11eb-9dc0-51efd117162a.png">
> 
> if you click voila you will have your graph rendered. And any other widgets.

I get it. Thanks.

**Comment by caraevangeline** [comment]
Okay:-)

> In the coming days I will publish a second article in the series in medium Exactly with the problem you mentioned.
> stay tuned.
> now I think you can close.
