### ISSUE TITLE
Article in medium for commenting (part 2 of learning graphs with ipycytoscape)

### ISSUE THREAD

**Issue by joseberlines** [QuantStack/ipycytoscape#204]
Dear @marimeireles & @ianhi,

I have ready a second article:
https://joseberlines.medium.com/part-2-learning-graphs-with-ipycytoscape-the-train-rail-net-grows-up-db2daa2f453d

it is yet unlisted.
If you have time the coming days can you please have a look and make any comment here before I made it available to everyone?

thanks

**Comment by ianhi** [comment]
Hi @joseberlines, it's awesome that you're writing things like this. Overall I think that this could be very helpful to someone starting out learning how to visualize graphs! Content wise I don't think you've any mistakes, however one really nice improvement to the graphs could be to make the sizes of the edges correspond to the speed of that train connection.

I also have a few practical notes:
1. It would be nice to have a link to the first article at the beginning
2. Some of the lists don't seem be formatting such that they are properly indented. For example I'd expect this to have each point indented: 
![image](https://user-images.githubusercontent.com/10111092/102167451-6a85d080-3e5c-11eb-9daa-fc1dca9bc631.png)
3. There are some grammar and spelling errors scattered throughout. For stuff like this I like using https://www.grammarly.com/ as it will help with phrasing in addition to the spelling of words.

**Comment by joseberlines** [comment]
Thanks. I will revisit grammar. My English is quite ok but i am not used to write articles.

**Comment by joseberlines** [comment]
Can you give me a hand here?

> Hi @joseberlines, ... however one really nice improvement to the graphs could be to make the sizes of the edges correspond to the speed of that train connection.

I would love to do that but:

I see in the style file of the Gene graph the following:
"width": "mapData(score, 0, 0.006769776522008331, 20, 60)",
"height": "mapData(score, 0, 0.006769776522008331, 20, 60)",

So it looks like it is proportional to the score.

Why width and height if they are circles? I would expect a unique parameter like radius.

In the same file I see that there is another node with shape "rectangle" but that one without height and width.

Let me know how you pass the size and I would add it to the notebook and article.

thx

**Comment by marimeireles** [comment]
Hey @joseberlines check it out this part of the docs: https://js.cytoscape.org/#getting-started/specifying-basic-options
I think it might help, they have a json tweaking edges:

```
     selector: 'edge',
      style: {
        'width': 3,
        'line-color': '#ccc',
        'target-arrow-color': '#ccc',
        'target-arrow-shape': 'triangle',
        'curve-style': 'bezier'
      }
```
