### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#209]
There have been 80 commits to master since the last release of 1.0.4 which primarily seem to have come from docs PRs and from #109 I think it would be nice to release these changes as there have been some issues popping up that are solved on the master branch but are not yet released.

This would at the very least deserve a bump to `1.1.0`, possibly a major version as well as some niches parts of #109 may be backwards incompatible.

@marimeireles I don't know how permissions on pypi/npm work for quantstack projects, but if you're able to add me to those projects I'd be happy to do the release.

**Comment by marimeireles** [comment]
Sorry I missed it @ianhi.
I'm always trying to merge all the PRs before making a release but lately it's been hard. That's why I dragged it for so long :(
I'll try to give you permissions for that :)
We can talk on private. Will make a new release right now.
Thanks for the reminder.

**Comment by marimeireles** [comment]
Done :)
New release out in pypi and you're invited as a maintainer.
To upload to pypi, create an account, I think you have to install sdist and twine. And the do the following:
```
git clean -fdx
python setup.py sdist
python setup.py bdist_wheel
twine upload dist/ipycytoscape*
```
After that the bot will pick up your changes on conda feedstock and you can merge the PR. Takes about an hour for that to happen, you can also do it manually by changing the hash of the file.
You're also invited for conda feedstock :)
Lemme know if you have any questions
