### ISSUE TITLE
How to change rendering space for ipycytoscape graph when rendering with voila.

### ISSUE THREAD

**Issue by joseberlines** [QuantStack/ipycytoscape#212]
Imaging you are building a graph that you later on want to render with voila is is possible to somehow specify that the space in which the graph is to be plotted should be bigger or of a particular dimension
<img width="1014" alt="Screenshot 2020-12-16 at 22 26 06" src="https://user-images.githubusercontent.com/33203439/102408735-5671d880-3fee-11eb-8244-d0c80254293f.png">
?

**Comment by marimeireles** [comment]
Huh, I'm not really sure @joseberlines. You might have more luck asking on the [voila](https://github.com/voila-dashboards/voila/) repo or at the QuantStack room https://gitter.im/QuantStack/Lobby

**Comment by joseberlines** [comment]
Thanks.

**Comment by marimeireles** [comment]
No probs. I think https://github.com/voila-dashboards/voila-gridstack might be what you're looking for.
But really don't know much about it.
Good luck :)

**Comment by ianhi** [comment]
@joseberlines can you try to modify the height of the cytoscape object by doing:
```python
G.layout.height = '1000px'
```

I chose 1000px because it is big, but I think that that string can be any valid css for defining the height
