### ISSUE TITLE
Restore lazy loading

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#221]
### Problem
We used to lazy load our js, but that got lost in the transition to jlab 3 due to issues when building the wheels. see https://github.com/QuantStack/ipycytoscape/pull/171#discussion_r551487495

### Proposed Solution
Bring back the lazy loading.

**Comment by marimeireles** [comment]
Hey Ian and @bollwyvl, thanks :)
Does this https://github.com/QuantStack/ipycytoscape/commit/71a61769fc843a7098b621287e1b84d5a8359afc close this issue?

**Comment by ianhi** [comment]
>  Does this 71a6176 close this issue?

Yup! Good catch
