### ISSUE TITLE
Remove @0.2.3 from jupyter-cytoscape in postBuild

### ISSUE THREAD

**Issue by sandertyu** [QuantStack/ipycytoscape#234]
### Problem

When trying to debug ipycytoscape in a [JupyterHub deployment](https://jupyter.libretexts.org/hub/login) that I help manage, I was testing a [repo2docker image](https://github.com/LibreTexts/default-env/tree/2.3.2) that we build with ipycytoscape=1.2.0 and it was not working because our jupyterlab=2.2. I was comparing the extensions used in the [postBuild](https://github.com/LibreTexts/default-env/blob/d25bd0204c940cf2efc8c69077054bda2b698a2d/postBuild#L22) of our environment against the one [in this repository](https://github.com/QuantStack/ipycytoscape/blob/1.2.0/postBuild) and noticed that the `jupyter-cytoscape` extension is pinned to `jupyter-cytoscape@0.2.3`. This is well out of date, and when actually built, `jupyter labextension list` shows `jupyter-cytoscape v1.2.0`;

![jupyter labextension list](https://cdn.discordapp.com/attachments/763198235237154837/808220669976379432/unknown.png)

### Proposed Solution

The pin for `@0.2.3` should probably simply be removed from postBuild. I've made a [PR](https://github.com/QuantStack/ipycytoscape/pull/233) to do this. Ipycytoscape has [code](https://github.com/QuantStack/ipycytoscape/blob/7f240158f6b690c304302e4cbab488c4c9c5159f/webpack.config.js#L58) to automatically match the ipycytoscape version to the labextension jupyter-cytoscape version anyways.

### Additional context

Furthermore, jupyter-cytoscape>1.0.4 does not seem to be hosted in this (somewhat?) official [npm repository](https://preview.npmjs.com/package/jupyter-cytoscape). I suggest that newer versions are either uploaded to here or it is made clear that this is an archived npm repository for jupyter-cytoscape that works only on jupyterlab2 and ipycytoscape<=1.0.4.

**Comment by marimeireles** [comment]
Thank  you for your issue and your fix @sandertyu.
So yeah, you're right about the npm repo, @ianhi and I forgot to upload the package there somehow!
I'll fix it right away and close this issue once it's fixed. Thanks for the catch!

**Comment by marimeireles** [comment]
Hey @sandertyu thanks again, fixed [here](https://www.npmjs.com/package/jupyter-cytoscape).
