### ISSUE TITLE
Only build JupyterLab in postBuild

### ISSUE THREAD

**Issue by sandertyu** [QuantStack/ipycytoscape#235]
### Problem

With the [extension changes](https://jupyterlab.readthedocs.io/en/latest/user/extensions.html#extensions) to JupyterLab3, most of the contents in the current `postBuild` of this repository are unnecessary. This can potentially be confusing for users seeking to replicate an environment like this one.

### Proposed Solution

I propose that the contents of `postBuild` are changed to simply `jupyter lab build --dev-build=False`. This could reduce potential errors in the future as JupyterLab continues to change and it improves clarity by removing redundant and unnecessary code. I have a [branch](https://github.com/LibreTexts/ipycytoscape/tree/reduce-postBuild) which can be built with binder to test the `postBuild` changes.

I was originally going to suggest removing `postBuild` entirely, but the `jupyter-offflinenotebook` extension got very mad and throws an [intrusive error](https://cdn.discordapp.com/attachments/729801592433410138/808493415515947028/unknown.png) on JupyterLab if you don't do `jupyter lab build` after installation. This extension comes from repo2docker which is still using JupyterLab2 and they [install it with `--no-build`](https://cdn.discordapp.com/attachments/763198235237154837/808501087756877873/offline-notebook.png). 

You also see this message when building without `postBuild`;
![no-postBuild](https://cdn.discordapp.com/attachments/729801592433410138/808492198885720086/labextension-binder.png)

I tested the [image](https://hub.docker.com/layers/libretexts/binder-dev-libretexts-2dipycytoscape-e057be/071cb5bd795258f5d282dd1529e46c0f6aa76d48/images/sha256-ffb61319ffa268ef6ed7209bfe385d31aaec8b2e284d9ae9852a3164a1cdf673) using the branch linked above with [this notebook](https://github.com/QuantStack/ipycytoscape/blob/master/examples/Text%20on%20node.ipynb). Everything works properly as far as I can tell.

Here is the labextension list in binder using the linked image;
![binder-extension-list](https://cdn.discordapp.com/attachments/763198235237154837/808501665052753980/labextension-list-binder.png)

Here is the labextension list in a JupyterLab deployment using the linked image;
![jlab-extension-list](https://cdn.discordapp.com/attachments/763198235237154837/808501666629943366/labextension-list-jlab.png)

### Additional context

Really this is a decision that is up to the maintainers of the project. It's difficult to keep up with all the changes made to JupyterLab. I can make a PR from my forked branch if you all would like to make this `postBuild` change.

**Comment by marimeireles** [comment]
Hey @sandertyu, thank you for opening this issue.
I don't see a problem with adding your changes to the `postBuild`, the code that's there doesn't even work anymore afaic, because it's made to run with `jupyterlab2`.
My only problem is that I couldn't run your local branch for some reason! I used: https://mybinder.org/v2/gh/LibreTexts/ipycytoscape/master?filepath=examples
But if you want to open a PR, I'll be happy to merge.

**Comment by marimeireles** [comment]
Okay :)
magically worked now, for me.
Are you doing this because the current postbuild file is failing for you somehow or because it's wrong?

**Comment by sandertyu** [comment]
Sorry for the late response. The code there does not cause any explicit problems so far as I know, but it is at best superfluous, and could potentially cause bugs or version conflicts later on. Additionally, `jupyter-offlinenotebook` (installed through [repo2docker](https://github.com/jupyterhub/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.yml) and unavoidable) suggests adding `jupyter lab build --dev-build=False` anyways, so that should be included regardless. 

My branch is still available to merge, and I've created a pull request for it if you would like to do so.

**Comment by marimeireles** [comment]
Is this fixed @sandertyu ?
Thanks!

**Comment by sandertyu** [comment]
> Is this fixed @sandertyu ?
> Thanks!

Yes I believe so. postBuild was removed as it was unnecessary. I'll close the issue now.
