### ISSUE TITLE
Support Voila

### ISSUE THREAD

**Issue by gqpj** [QuantStack/ipycytoscape#24]
Open in [voila](https://github.com/voila-dashboards/voila): 
```
http://localhost:8888/voila/render/ipycytoscape/examples/Test%20NetworkX%20methods.ipynb
```
I've got empty page with text "Test NetworkX methods [1, 5]"

In the network log I see 404 for urls:
* http://localhost:8888/voila/jupyter-cytoscape.js
* https://unpkg.com/jupyter-cytoscape@0.1.4/dist/index.js

**Comment by SylvainCorlay** [comment]
Are you trying to use ipycytoscape master?

**Comment by gqpj** [comment]
My install:
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-cytoscape
```

**Comment by SylvainCorlay** [comment]
What about the Python side?

**Comment by gqpj** [comment]
Python from miniconda:
```
$ python --version                                                                                                
Python 3.7.6
```

**Comment by SylvainCorlay** [comment]
I meant, what version of ipycytoscape are you using on the back-end?

**Comment by gqpj** [comment]
How to check it?

**Comment by marimeireles** [comment]
If you're using conda I think `conda list` should list your packages versions.

**Comment by marimeireles** [comment]
And thanks for opening the issues! =)

**Comment by gqpj** [comment]
```
$ conda list | grep cyto                                                                                          
ipycytoscape              0.1.3                    pypi_0    pypi
```

**Comment by SylvainCorlay** [comment]
Ah, I understand the issue. Fix coming up.

**Comment by SylvainCorlay** [comment]
Can you try again?

**Comment by SylvainCorlay** [comment]
(Without changing anything locally)

**Comment by gqpj** [comment]
> (Without changing anything locally)

It works! But http://localhost:8888/voila/jupyter-cytoscape.js still 404. Is it ok?

**Comment by SylvainCorlay** [comment]
> But http://localhost:8888/voila/jupyter-cytoscape.js is still 404. Is it ok?

Yes, this is a hook for developers to put a custom local version of the bundle. We use it for debugging locally before publishing.

**Comment by gqpj** [comment]
Great! Thanks! :+1:
