### ISSUE TITLE
For info: A new tag exists in Stackoverflow for ipycytoscape

### ISSUE THREAD

**Issue by joseberlines** [QuantStack/ipycytoscape#242]
The title says it all.
There was not yet such a tag so the whole community will be able now to post questions in StackOverflow and tag them with:

![image](https://user-images.githubusercontent.com/33203439/109004165-adf48a80-76a8-11eb-9557-ad062acd4fa5.png)

**Comment by marimeireles** [comment]
Hey @joseberlines, thank you!
And sorry, I was out for a little vacation.
I'll keep this open so we remember to add a tag on the readme! :)

**Comment by joseberlines** [comment]
There are some questions in SO already about ipycytoscape. It's my intention to tag them if I have permissions.

**Comment by marimeireles** [comment]
>It's my intention to tag them if I have permissions.

Do you? Or do I have to do something somewhere?

**Comment by joseberlines** [comment]
Dont worry I will take care of this (if I have permissions to tag others questions). Next time I look for something I will try to Tag and report here. Then I will close issue herw

**Comment by marimeireles** [comment]
Thank you very much for using your privileges @joseberlines :)
