### ISSUE TITLE
redering a ipycytoscape as a tree

### ISSUE THREAD

**Issue by joseberlines** [QuantStack/ipycytoscape#243]
Anyone knowing what is the layout necessary to use in order to get a layout like this:
https://stackoverflow.com/questions/66351266/rendering-a-graph-as-a-tree
![image](https://user-images.githubusercontent.com/33203439/109331228-e2a94300-785c-11eb-8f25-c76f78b15575.png)

What it is necessary to achieve is that parents are higher than children.
Thanks

**Comment by timkpaine** [comment]
you can see a good overview of cytoscape layouts and demos on https://js.cytoscape.org/

**Comment by timkpaine** [comment]
Example: https://github.com/QuantStack/ipycytoscape/blob/7f240158f6b690c304302e4cbab488c4c9c5159f/examples/DAG%20example.ipynb

**Comment by joseberlines** [comment]
thanks @timkpaine
