### ISSUE TITLE
Graph display is not cleared when nodes, edges and adjacency are cleared 

### ISSUE THREAD

**Issue by SebastienDorgan** [QuantStack/ipycytoscape#255]
### Bug report

**Bug summary**
I add a graph using
```python
self.cyto.graph.add_graph_from_networkx(G)
```
where self.cyto is an instance of CytoscapeWidget.
The graph is correctly displayed
![image](https://user-images.githubusercontent.com/12728415/116415092-5fdf3d00-a839-11eb-8d1e-7abd43fa4b9e.png)

To clear I use: 
```python
def clear_graph(self):
    self.cyto.graph.edges.clear()
    self.cyto.graph.nodes.clear()
    self.cyto.graph._adj.clear(
```
But the graph is still displayed

**Environment**
Python 3.8.5

ipycytoscape              1.2.0              pyhd8ed1ab_0    conda-forge
ipython                   7.22.0           py38hb070fc8_0  
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge

**Comment by SebastienDorgan** [comment]
Installing ipycytoscape from the source solved the problem

**Comment by marimeireles** [comment]
I believe this was fixed by the newest release.
Thanks for opening the issue!
