### ISSUE TITLE
Is it possible to set the concentric variable in ipycytoscape?

### ISSUE THREAD

**Issue by micw42** [QuantStack/ipycytoscape#257]
In the concentric layout of cytoscape.js, it is possible to put a node in a certain "layer" of the circle through the `concentric` variable of the layout:

```
concentric: function( node ){ 
      return node.data("rank");
  }
```

[Here](https://js.cytoscape.org/#layouts/concentric)  is the cytoscape.js documentation about this

Is there a similar function to this in ipycytoscape? Thank you so much!

**Comment by ianhi** [comment]
Hi @micw42 good question! I think you're looking for the code in this example: https://github.com/QuantStack/ipycytoscape/blob/master/examples/Concentric%20example.ipynb

Hope that works for you!

**Comment by micw42** [comment]
Hi @ianhi Thank you for answering my question! Sorry I wasn't being very clear before. I've already done`cytoscapeobj.set_layout(name='concentric')` I was wondering if there were a way to control which concentric layer a node ends up in? For example, here is the graph I made:

![image](https://user-images.githubusercontent.com/70285403/117234537-0c8d6180-adda-11eb-9d86-bfa2e6af27bf.png)


Would it be possible to make the red node on the left be in the center? Cytoscape.js allows you to set a function that determines which layer a node is in, so I wonder if this is also possible in ipycytoscape? Thank you so much for your help; I really appreciate it :)

**Comment by marimeireles** [comment]
Hey @micw42, thanks for opening the issue.
I think the reason why you can't do this is the same as: https://github.com/QuantStack/ipycytoscape/issues/238?
What do you think? If it is, we can close this issue and keep the discussion centralized in there.
For now we don't have a fix! But feel free to add your thoughts and questions there. I can't work on it at the moment but would gladly review a PR if you wanna try it! :)
Cheers.

**Comment by micw42** [comment]
Hey @marimeireles Yeah, I think it's the same; sorry I didn't see it earlier! Thank you :)

**Comment by marimeireles** [comment]
No probs! :)
