### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by gqpj** [QuantStack/ipycytoscape#29]
Just want to let you know that you can use WebGL for draw graph like plotly https://plotly.com/python/webgl-vs-svg/

**Comment by martinRenou** [comment]
`Cytoscape.js` does not support using a GL context as far as I can see. But it's using the 2D context of a Web Canvas. Which is already relatively fast. You can also go up to a million points, not as smooth as WebGL but still way faster than SVG.

**Comment by marimeireles** [comment]
Thanks for the feedback @martinRenou!
@gqpj if you're interested in talking or getting involved somehow QuantStack has an open channel on gitter that you can join: https://gitter.im/QuantStack and https://gitter.im/QuantStack/core_development, thanks for the issue =)

**Comment by gqpj** [comment]
Thank you for explanation! I'm going to close this.
