### ISSUE TITLE
Make tip visualization better

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/ipycytoscape#33]
The visualization looks cramped now if you add more than one attribute to the tip. It's not possible to add line breaks. I think adding that would be enough already.

<img width="186" alt="Screen Shot 2020-04-13 at 11 56 19 AM" src="https://user-images.githubusercontent.com/17600982/79111985-14143f80-7d6d-11ea-8d9d-61b89618eef1.png">

Maybe upgrading to a new tip version will fix this.

**Comment by marimeireles** [comment]
The way cytoscape.js is dealing with this is writing some non generalist code in the frontend, but might give me some good ideas about how to improve the visualization: https://js.cytoscape.org/demos/colajs-graph/

**Comment by ianhi** [comment]
You can add line breaks with `<br />`. I just tried manually adding some and it worked. 

A first pass for improvment would be to replace all line breaks with a `<br />`
using a regex from: https://stackoverflow.com/questions/784539/how-do-i-replace-all-line-breaks-in-a-string-with-br-elements


```javascript
content.innerHTML = node.data().name.replace(/(?:\r\n|\r|\n)/g, '<br>');
```

https://github.com/QuantStack/ipycytoscape/blob/8769ec2d36a9ae5ec8420ffc1c96fbb0f062d284/src/widget.ts#L371-L373

**Comment by marimeireles** [comment]
Oh, that's sweet! :D

> Also, currently the only way to use a tip is to store the data in name, it would also be nice to store the tip data in a dedicated attribute inside data.

That's a very good idea, the `data` attribute in cytoscape is a free thing, right? Is up to the users to decide what kind of content it will have.

Another option, would be making this method more generic, allowing the user to choose which attribute of the graph they'd like to use it as tip.

**Comment by ianhi** [comment]
> allowing the user to choose which attribute of the graph they'd like to use it as tip.

I do like having choices :)

How about there being a default attribute to use (stored in data) e.g. `onclick-text` and it is also configurable via the constructor of the cytoscapewidget https://github.com/QuantStack/ipycytoscape/blob/8769ec2d36a9ae5ec8420ffc1c96fbb0f062d284/ipycytoscape/cytoscape.py#L273

**Comment by marimeireles** [comment]
Closed by https://github.com/QuantStack/ipycytoscape/pull/74 but we can still make it better, see https://github.com/QuantStack/ipycytoscape/issues/81.
Thanks a lot for your work here @ianhi :))
