### ISSUE TITLE
kernel restart causes cytoscape widget to grow forever

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#50]
![restarting_kernel](https://user-images.githubusercontent.com/10111092/80659033-bf9fde00-8a55-11ea-8bca-6a68eaffc6e2.gif)
This isn't the biggest deal as it doesn't occur while the kernel is live. But restarting the kernel is definitely something I do often enough that I could see this being annoying. Unfortunately I don't have any insight as to why this happening. 

Of note: it only expands until it is out of view, it will only expand more once you scroll down

## Context:
jupyterlab == 2.1.1 
ipycytoscape == master branch
browser: firefox 75.0 and chrome 80.0
OS: PopOs 19.10 (basically Ubuntu 19.10)

**Comment by marimeireles** [comment]
Thanks for posting @ianhi. Fixed in master :)
