### ISSUE TITLE
use eslint for typescript

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#65]
Something I found pretty useful in making jupyterlab extensions (rather than widgets) is the automatic linting of typescript code using eslint. Adding eslint as a dev dependency would allow for running: `npm run lint` to automatically style the typescript code (e.g. https://github.com/jupyterlab/jupyterlab-git/blob/8d56986409461cd9968d7208da4946fca8c70392/package.json#L23-L25). You can also add it to the the checks that happen on opening PRs https://github.com/jupyterlab/jupyterlab-git/blob/8d56986409461cd9968d7208da4946fca8c70392/.travis.yml#L15

Given that this is more of a python first project this may not be necessary, but thought I'd raise the idea.

FWIW this is included by default in the extension-ts-cookiecutter, but not in the widget-ts-cookiecutter

**Comment by marimeireles** [comment]
No, I think it's equally a .ts project, it's just that I'm way better in python, so I tend to write more python.
That's a good idea :)

**Comment by ianhi** [comment]
I too am better at python than typescript. Which I think is why I found the compilation of typescript and linting so helpful!
