### ISSUE TITLE
Allow using kwargs when creating cytoscapewidget

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#73]
It'd be nice to be able to define widget attributes at creation time, rather than after.

i.e.:

```python
style = .....
cytoscapeobj1 = ipycytoscape.CytoscapeWidget(cytoscape_style = style)
cytoscapeobj2 = ipycytoscape.CytoscapeWidget(cytoscape_style = style)
```
instead of
```python
style = .....
cytoscapeobj1 = ipycytoscape.CytoscapeWidget()
cytoscapeobj2 = ipycytoscape.CytoscapeWidget()
cytoscapeobj1.set_style(style)
cytoscapeobj2.set_style(style)
```

This could either be implemented as explicit keyword arguments to `init`, or maybe  `init` could accept `**kwargs`.

**Comment by ianhi** [comment]
Fixed by: https://github.com/QuantStack/ipycytoscape/pull/92

**Comment by marimeireles** [comment]
Thanks @ianhi!
