### ISSUE TITLE
How do I listen to onclick events for Node or Edge

### ISSUE THREAD

**Issue by panicfarm** [QuantStack/ipycytoscape#79]
I would like to be able to register listeners for all Edges and Nodes such that when a user clicks on them, a callback with the Edge.data or Node.data is called.

Is this already possible?

**Comment by ianhi** [comment]
It's not possible.... yet

If you wanted to have a go at implementing it you would need to listen to events with the cytoscapejs functions:
https://js.cytoscape.org/#core/events
The function listening to these events should then send a message back to python (`this.model.send`) with which node was selected.

Then on the python side this should be handled by a `CallbackDispatcher` to manage user callbacks. The best example is probably the button widget:
typescript: https://github.com/jupyter-widgets/ipywidgets/blob/6be18d9b75353f7b4a1c328c6ea06d8959f978f6/packages/controls/src/widget_button.ts#L119-L122
python: https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget_button.py

my understanding of this comes from this conversation: https://gitter.im/QuantStack/Lobby?at=5ecd7dc727513a72fbb4b783

**Comment by timkpaine** [comment]
A similar example:
JS side: https://github.com/timkpaine/ipydagred3/blob/master/js/src/view.ts#L74
Python side track click handlers: https://github.com/timkpaine/ipydagred3/blob/master/ipydagred3/widget.py#L31
Python side register on click: https://github.com/timkpaine/ipydagred3/blob/master/ipydagred3/widget.py#L34
Python side handle JS messages:
https://github.com/timkpaine/ipydagred3/blob/master/ipydagred3/widget.py#L40

**Comment by marimeireles** [comment]
I'm not sure if I completely grasp what's your objective with this.
Currently we have this click event:

https://github.com/QuantStack/ipycytoscape/blob/42241912d2323f0f6a8ed222eca36e6a1cd9bf31/src/widget.ts#L402-L433

and it responds to user interactions.
For example if I add a console log to this click event:

<img width="1678" alt="Screen Shot 2020-06-17 at 11 39 34 PM" src="https://user-images.githubusercontent.com/17600982/84953448-0cfa0c80-b0e3-11ea-8b5f-c044bbf88273.png">

Every time I click the node I get a response.
So I think it'd be fairly easy to create a method to tweak around with data.

What's your objective @panicfarm? You want to show some specific part of data if you click the node?

**Comment by marimeireles** [comment]
Thank you for your inputs @ianhi and @timkpaine, much appreciated :)

**Comment by timkpaine** [comment]
I think they want to subscribe in python, like in this example:
![https://raw.githubusercontent.com/timkpaine/ipydagred3/master/docs/img/example2.gif]()

**Comment by panicfarm** [comment]
@marimeireles @timkpaine 's comment is right: we are plotting a subgraph  of a huge graph, and when a user clicks on a node, we would like to add dynamically all edges (and nodes where they terminate) that originate in the clicked node, that are not in the displayed sub-graph.

**Comment by stefco** [comment]
I would also find this useful; I use an interactive graph to select steps in a pipeline DAG I built in a GUI.

@marimeireles if you're accepting pull requests, I'd be happy to try to add this feature in, maybe just by setting a "value" trait on the widget to the last selected node on click. I could use a different trait name if you want to reserve `value`. Does that sound like an acceptable approach?

**Comment by stefco** [comment]
@marimeireles @timkpaine @panicfarm I've added this feature in #97. You can specify which types of events to `monitor` from the [the full list of cytoscape events](https://js.cytoscape.org/#events/user-input-device-events) for either `'node'` or `'edge'` objects and then `observe` the last input in the `last_user_event` trait in the kernel. It's pretty general, so it should work for any use case that an in-browser event handler would. You specify the events to monitor with a keyword arg like `monitored={'node': ['click']}` and get `last_user_event` updates that look like `{'type': 'node', 'event': 'click', 'target': {'id': 'LvcGcnXml'}}`. Example in [this notebook](https://github.com/stefco/ipycytoscape/blob/user-interaction/examples/interaction-example.ipynb) using my pipeline's graph.

I also added the `cytoscape-klay` layout since this is very useful for me, but if this isn't something you want to put in the widget, let me know and I'll remove that from the pull request since it is completely orthogonal. Also let me know if you'd prefer a somewhat different interface.

Mariana, thank you for making such a lovely library!

**Comment by marimeireles** [comment]
I thought your approach was very interesting, looking forward to merge it! :)
We just have to figure out the problem with the other graphs.

Thank you for the contribution! :cherry_blossom:

**Comment by stefco** [comment]
Okay, implemented this in #97. You can now add listeners with the [`CytoscapeWidget.on` method](https://github.com/stefco/ipycytoscape/blob/user-interaction/ipycytoscape/cytoscape.py#L464). You specify the type of widget to listen for (currently "node" or "edge") as well as the type of event to listen for (e.g. "click", though any of the [supported cytoscape.js events](https://js.cytoscape.org/#events/user-input-device-events) can be used) and a callback to run when such an event occurs (taking the "data" attribute of the widget as its only argument). Works similarly to `ipywidgets.Button.on_click`, though you can specify a full range of interaction types. You can dynamically add or remove callbacks from the kernel at any point in the object's lifetime using this interface.

**Comment by marimeireles** [comment]
Fixed by @stefco, thank you very much =)
