### ISSUE TITLE
Add pixelRatio attribute to ipycytoscape

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/ipycytoscape#83]
While pursuing a solution for #77 on PR #78 @ianhi found out about an attribute that can either be a float or a string:

https://js.cytoscape.org/#init-opts/pixelRatio

We don't quite know how to deal with that with traitlets, but might be an interesting exploration.

**Comment by martinRenou** [comment]
You can use an `Union`, so something like: `Union(Unicode(), CFloat())` should work

**Comment by marimeireles** [comment]
Huh! That was way simpler than I expected.
Thanks @martinRenou  :D

**Comment by ianhi** [comment]
Wow don't know how I missed that. Thanks @martinRenou! through your comments here and my reading of the ipycanvas source code I think you're becoming the main source of my understanding of jupyter widgets.
