### ISSUE TITLE
Use of `curve-style: bezier` is necessary to add directed style to graphs

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/ipycytoscape#87]
I was reading the [docs](https://js.cytoscape.org/#style/bezier-edges) of this property and it really doesn't make much sense to me why this is happening.

_Originally posted by @marimeireles in https://github.com/QuantStack/ipycytoscape/pull/70_

**Comment by marimeireles** [comment]
Have to test it again on mac.

**Comment by ianhi** [comment]
It's not in the docs but just found the SO answer by the maintainer of ipycytoscape:
https://stackoverflow.com/a/37843786/835607

seems that it is indeed necessary

**Comment by marimeireles** [comment]
Yeah, that's weird-ish.
Maybe we should just ask him, doesn't seem like smth the API should have right?
Thanks for digging this out @ianhi =)
