### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#88]
With some of the recent merges I find that the master branch is substantially more useful to me than the latest release. Any chance of `0.3.0` release? It would make sharing this with some of my friends and collaborators much easier (no need to have them git clone anything...), I think it would also clear up https://github.com/QuantStack/ipycytoscape/issues/82

Maybe it would be worth dealing with :
https://github.com/QuantStack/ipycytoscape/issues/83
and https://github.com/QuantStack/ipycytoscape/issues/64#issuecomment-645064201
before releasing a new version

**Comment by marimeireles** [comment]
I think we could do a `0.2.3` release before fixing this stuff.
I think it'd be cool to merge the two PRs that are hanging for a `0.3.0`? I'm not sure, we might even have to release a 1.0.0 because I think we're gonna break compatibility. I'm mostly following [this](https://semver.org/) to make the choice.
I'll release a `0.2.3` now :)

**Comment by marimeireles** [comment]
It's already out on npm and pypi, I'll soon make a conda package for it (once the bot catches my release) but you can already use it with `pip` if you want to.
Thanks for your work around here @ianhi!

**Comment by marimeireles** [comment]
Okay, everything done!
Including the conda stuff. :)

**Comment by ianhi** [comment]
hooray thanks! 


>we might even have to release a 1.0.0 because I think we're gonna break compatibility


My understanding of semver was that pre 1.0.0 there are no expectations of backwards compatibility
[ref](https://semver.org/#spec-item-4)
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
