### ISSUE TITLE
Optimize communication with front-end

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/ipycytoscape#93]
At this place in the code: https://github.com/QuantStack/ipycytoscape/blob/master/ipycytoscape/cytoscape.py#L226-L229, we loop over all the nodes of the JSON file, and `append` new values to the `MutableList` structure. This will have the effect of sending as many update messages to the front-end as there are nodes in the structure.

It might be preferable to loop over the JSON, constructing the node instances, and only once all the node instances are created we should assign the list of nodes to the `nodes` attribute. This will have the effect of sending **one** update message.

**Comment by marimeireles** [comment]
That's a good catch, thanks @martinRenou!

**Comment by ianhi** [comment]
The `from_networkx` function could use the change. The dataframe method already seems to have this optimization.
