### ISSUE TITLE
add spaces to classes when using directed=True

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#95]
cytoscapejs expects the classes to either be an array of strings or a string with classes separated by spaces. Currently when creating a graph with `directed=True` then a `directed` class will be added without any spaces. This works if there aren't any classes already present, but should break if there are any classes already present.
https://github.com/QuantStack/ipycytoscape/blob/b662ec1538564676ffc0c2334ff77dd407a7a1a0/ipycytoscape/cytoscape.py#L210

Maybe we could switch to using a list of strings for the classes? I think this would remove ambiguities as to whether spaces need to be added. We could also use a traitlets Union here but I think life would be made easier sticking to either strings or arrays.

**Comment by marimeireles** [comment]
Thanks!! 🌸🌸🌸
