### ISSUE TITLE
Class selectors in examples not working

### ISSUE THREAD

**Issue by blackvvine** [QuantStack/ipycytoscape#98]
Hi, 

I just installed version 0.2.3 with Jupyter 6.0.3 and the latest Jupyter labs extension, and the class selectors didn't seem to be working. After an hour of struggling, I tried the examples and noticed the class selectors don't work in the "labels" example either:

<img width="861" alt="Screen Shot 2020-06-21 at 6 08 33 PM" src="https://user-images.githubusercontent.com/9886871/85236261-6f585300-b3ea-11ea-9acf-6dff3241edbf.png">

**Comment by ianhi** [comment]
Oh huh. good catch!

I think this is specific to the `from_json` method. The attributes other than data never get added:
https://github.com/QuantStack/ipycytoscape/blob/b662ec1538564676ffc0c2334ff77dd407a7a1a0/ipycytoscape/cytoscape.py#L226-L230

Compare to the `networkx` method:
https://github.com/QuantStack/ipycytoscape/blob/b662ec1538564676ffc0c2334ff77dd407a7a1a0/ipycytoscape/cytoscape.py#L189-L201

The `from_json` needs the equivalent

**Comment by ianhi** [comment]
@blackvvine should be fixed by the linked PR

**Comment by marimeireles** [comment]
Thanks for the report @blackvvine!

**Comment by marimeireles** [comment]
& super thanks to @ianhi for fixing it <3
